#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-powershell
Version  : 0.3.3
Release  : 2
URL      : https://files.pythonhosted.org/packages/c8/7a/26612eb3a1b1dcd1ca69177c74d172dac7563f1c392f2067f6a2e148046a/colcon-powershell-0.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/c8/7a/26612eb3a1b1dcd1ca69177c74d172dac7563f1c392f2067f6a2e148046a/colcon-powershell-0.3.3.tar.gz
Summary  : Extension for colcon to provide PowerShell scripts.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-powershell-python3
Requires: colcon-powershell-python
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
=================

%package python
Summary: python components for the colcon-powershell package.
Group: Default
Requires: colcon-powershell-python3

%description python
python components for the colcon-powershell package.


%package python3
Summary: python3 components for the colcon-powershell package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-powershell package.


%prep
%setup -q -n colcon-powershell-0.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533002860
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
