#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-powershell
Version  : 0.3.4
Release  : 4
URL      : https://files.pythonhosted.org/packages/71/47/09e63a06b4d4df417323f37e4bb13a2629f41c8cea31dc3bbd7bc1d8d69f/colcon-powershell-0.3.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/71/47/09e63a06b4d4df417323f37e4bb13a2629f41c8cea31dc3bbd7bc1d8d69f/colcon-powershell-0.3.4.tar.gz
Summary  : Extension for colcon to provide PowerShell scripts.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-powershell-python = %{version}-%{release}
Requires: colcon-powershell-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3

%description
colcon-powershell
=================
An extension for `colcon-core <https://github.com/colcon/colcon-core>`_ to provide `PowerShell <https://github.com/PowerShell/PowerShell>`_ scripts.

%package python
Summary: python components for the colcon-powershell package.
Group: Default
Requires: colcon-powershell-python3 = %{version}-%{release}

%description python
python components for the colcon-powershell package.


%package python3
Summary: python3 components for the colcon-powershell package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-powershell package.


%prep
%setup -q -n colcon-powershell-0.3.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551476399
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
