#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-powershell
Version  : 0.3.6
Release  : 12
URL      : https://files.pythonhosted.org/packages/c2/be/fbcd45cdeda666c5626deb65e2405c76516d4436fc19beb6de6408db31b5/colcon-powershell-0.3.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/c2/be/fbcd45cdeda666c5626deb65e2405c76516d4436fc19beb6de6408db31b5/colcon-powershell-0.3.6.tar.gz
Summary  : Extension for colcon to provide PowerShell scripts.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-powershell-python = %{version}-%{release}
Requires: colcon-powershell-python3 = %{version}-%{release}
Requires: colcon-core
BuildRequires : buildreq-distutils3
BuildRequires : colcon-core

%description
=================

%package python
Summary: python components for the colcon-powershell package.
Group: Default
Requires: colcon-powershell-python3 = %{version}-%{release}

%description python
python components for the colcon-powershell package.


%package python3
Summary: python3 components for the colcon-powershell package.
Group: Default
Requires: python3-core
Provides: pypi(colcon_powershell)
Requires: pypi(colcon_core)

%description python3
python3 components for the colcon-powershell package.


%prep
%setup -q -n colcon-powershell-0.3.6
cd %{_builddir}/colcon-powershell-0.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583528519
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
